{% set name = "quackosm" %}
{% set version = "0.15.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/quackosm-{{ version }}.tar.gz
  sha256: 21e58eb55ed4773f92665956a711534086d095b7ce19ac8dba56e0ab680e33af

build:
  entry_points:
    - quackosm = quackosm.__main__:main
    - QuackOSM = quackosm.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pdm-backend
    - pip
  run:
    - python >={{ python_min }}
    - geopandas >=0.6
    - shapely >=2
    - pyarrow >=16.0.0
    - python-duckdb >=1.1.2
    - geoarrow-pyarrow >=0.1.2
    - typeguard >=3.0.0
    - psutil >=5.6.2
    - pooch >=1.6.0
    - tqdm >=4.42.0
    - beautifulsoup4
    - requests
    - polars >=1.9
    - rich >=12.0.0
    - geopy >=2.0.0
    - numpy >=1.26.0
    - rq_geo_toolkit >=2025.6.1
   # Extra: cli
    - typer >=0.9.0
    - python-geohash >=0.8
    - s2sphere >=0.2.5

test:
  imports:
    - quackosm
  commands:
    - pip check
    - quackosm --help
    - QuackOSM --help
    - quackosm --osm-extract-query Monaco --osm-extract-source Geofabrik
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/kraina-ai/quackosm
  summary: An open-source tool for reading OpenStreetMap PBF files using DuckDB
  license: Apache-2.0
  license_file: LICENSE
  description: |
    QuackOSM is an OpenStreetMap data downloader and reader for Python 3.9+.
    It can work with bigger-than-memory PBF files and transform them into
    GeoParquet files with proper geometries. It is built on top of DuckDB's
    spatial extension with a dedicated CLI.
  doc_url: https://kraina-ai.github.io/quackosm/
  dev_url: https://github.com/kraina-ai/quackosm

extra:
  recipe-maintainers:
    - RaczeQ
